name: Op

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "jaymalav10@gmail.com"
  GitHubName: "vijaymalav564" 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          sudo apt install python3 python3-pip
          pip3 install -r requirements-cli.txt
          sudo docker build . -t wzmlx
          sudo docker run -p 80:80 -p 8080:8080 wzmlx
